analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.6424958
  lightness: 0.7816189
  brandStrength: 0.6357504
  brandColors:
    - '#91919B'
    - '#FBFCFB'
    - '#B4CFE1'
    - '#3B6EA1'
    - '#433920'
  rhythmicContrast: 0.7689713
typography_spectrum: 0
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0
favicon: null
name: InfinitePerspective
